tacticool is foldable now
impstation/imp-station-14 pull request #799
Opened 2024-11-25 15:43 UTC by Sha-Seng

i played around with making a "pulled down, but still visible" neck gaiter sprite but i didn't like it.  so to finish the hacked clothesmate outfit, the tacticool jumpsuit is foldable now.  oh and i added one more gas mask to the hacked inventory to follow the trend that the neck gaiters set, being "one jumpsuit, one jumpskirt, two neck gaiters" in that a hacked clothesmate can now provide two full operator larper fits (one suit, one skirt)

big black coats are very common in maints on all maps so i don't wanna add anything like that, go find your coat if you wanna do that look

outfit example below.  now you can be a watch dogs 1 character if you go electrocute yourself on the machine

![test11](https://github.com/user-attachments/assets/dd4e7d07-d21c-4731-9bc3-290bd31eca45)

:cl:
- tweak: tacticool and operative jumpsuits are now foldable
- tweak: gas mask stock in hacked clothesmate increased by one

2024-11-25 16:19 UTC, Pinkbat5 commented
Ohhhh this is driptastic. Yay
Isn't there a separate, syndicate version of the tacticool jumpsuit that nukies spawn with? Maybe add this folder sprite to that item too? Unless they use the same rsi file...

2024-11-26 02:42 UTC, hivehum requested changes

2024-11-26 02:42 UTC, hivehum commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
> +    ClothingMaskGas: 2
revert this part and i'll merge it. rest of the PR is fine

2024-11-26 03:10 UTC, hivehum approved these changes

2024-11-26 03:11 UTC, merged